version: '3'
services:
  web_estoque:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_estoque
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=applications
      - DB_USERNAME=fabio
      - DB_PASSWORD=mypass
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Cliente@site
      MYSQL_DATABASE: applications
      MYSQL_USER: fabio
      MYSQL_PASSWORD: mypass
    ports:
        - "3306:3306"
